name: Run, Store, and Publish Benchmarks
on:
    push:
        branches:
            - master

permissions:
    contents: write
    deployments: write

jobs:
    benchmark:
        name: Run FIARA.Benchmarks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout and Setup
            - uses: actions/checkout@v2
            - uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 7.0.x

            - name: Run Benchmarks
              run: cd src && dotnet run -c "Release" --project "FIARA.Benchmarks/FIARA.Benchmarks.csproj" --framework "net7.0" --filter "*" --exporters "json"

    publish:
        strategy:
            matrix:
                benchmarks: ["FIARA.Benchmarks.Substitutions.Vector2ConstructorBenchmark", "FIARA.Benchmarks.Substitutions.Vector2AddBenchmark", "FIARA.Benchmarks.Substitutions.Vector2SubtractBenchmark", "FIARA.Benchmarks.Substitutions.Vector2MultiplyBenchmark", "FIARA.Benchmarks.Substitutions.Vector2DivideBenchmark"]
        name: Store and Publish FIARA.Benchmarks
        runs-on: ubuntu-latest
        steps:
            - name: Store Resulting Benchmarks
              uses: rhysd/github-action-benchmark@v1
              with:
                  name: Benchmark.NET Benchmark
                  tool: "benchmarkdotnet"
                  output-file-path: src/BenchmarkDotNet.Artifacts/results/FIARA.Benchmarks-report-full-compressed.json
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  auto-push: true
                  alert-threshold: "200%"
                  comment-on-alert: true
                  fail-on-alert: true
                  alert-comment-cc-users: "@steviegt6"

            - name: Publish Resulting Benchmarks
              uses: rhysd/github-action-benchmark@v1
              with:
                  name: Benchmark.NET Benchmark
                  tool: "benchmarkdotnet"
                  output-file-path: src/BenchmarkDotNet.Artifacts/results/FIARA.Benchmarks-report-full-compressed.json
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  auto-push: true
                  alert-threshold: "200%"
                  comment-on-alert: true
                  fail-on-alert: true
                  alert-comment-cc-users: "@steviegt6"
                  gh-repository: "github.com/hcdotnet/fiara-fna-benchmarks"